// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseApp():Promise<void>;

export function OpenFile():Promise<main.FileResponse>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:boolean):Promise<string>;
