name: build-win

on:
  push:
    branches: ["mother"]
  pull_request:
    branches: ["mother"]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: false

      - name: Build Wails
        uses: dAppServer/wails-build-action@v2
        id: build-win
        with:
          build-name: nephrite-win
          build-platform: windows/amd64
          package: true
          go-version: "1.25"
          wails-version: "2.16.0"
