name: build

on:
  push:
    branches: [ "mother" ]
  pull_request:
    branches: [ "mother" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: false

      - name: Verify Podman Installation
        run: podman --version

      - name: Build Podman Image
        run: make pod-build
